#!/usr/bin/env node
/**
 * Packs the hand-made dungeons (../dungeon/*.txt, made with the original
 * level editor) into src/data/levels.generated.js.
 * Usage : npm run levels
 */
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.join(path.dirname(fileURLToPath(import.meta.url)), "..");
const source = path.join(root, "..", "dungeon");

const names = ["tuto"];
for (let i = 1; i <= 5; i++)
	names.push("adv_" + i);
for (let i = 1; i <= 7; i++)
	names.push("course_" + i);

const out = {};
for (const name of names) {
	const lines = fs.readFileSync(path.join(source, name + ".txt"), "latin1")
		.split(/\r?\n/)
		.map(l => l.trim())
		.filter(l => l !== "" && !l.startsWith("#"));
	if (lines.length < 64)
		throw new Error(name + " : incomplete file");
	out[name] = lines.slice(0, 64);
}

const js = "// Generated by tools/build_levels.js from ../dungeon/*.txt : do not edit.\n"
	+ "export default " + JSON.stringify(out, null, "\t") + ";\n";
fs.writeFileSync(path.join(root, "src", "data", "levels.generated.js"), js);
console.log("src/data/levels.generated.js : " + names.length + " dungeons");
