#!/usr/bin/env node
// Packs ../dungeon/*.txt (the mb2edit room assemblies fed to mb2gen) into
// js/data/levels.js so the game also works when opened from file:// (no fetch).
// Usage: node tools/build_levels.js
const fs = require("fs");
const path = require("path");

const root = path.join(__dirname, "..");
const src = path.join(root, "..", "dungeon");
const files = ["tuto"];
for (let i = 1; i <= 5; i++) files.push("adv_" + i);
for (let i = 1; i <= 7; i++) files.push("course_" + i);

const out = {};
for (const f of files) {
	const lines = fs.readFileSync(path.join(src, f + ".txt"), "latin1")
		.split(/\r?\n/)
		.map(l => l.trim())
		.filter(l => l !== "" && l[0] !== "#");
	if (lines.length < 64) throw new Error(f + ": incomplete file");
	out[f] = lines.slice(0, 64);
}

const js = "// Generated by tools/build_levels.js from ../dungeon/*.txt - do not edit\n"
	+ "MB2.LEVEL_FILES = " + JSON.stringify(out, null, "\t") + ";\n";
fs.writeFileSync(path.join(root, "js", "data", "levels.js"), js);
console.log("wrote js/data/levels.js (" + files.length + " dungeons)");
